# Generated by Django 3.0.6 on 2020-05-07 06:01

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('module_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='名字')),
                ('link', models.CharField(max_length=255, verbose_name='落地页')),
                ('language', models.CharField(default='中文简体', max_length=255, verbose_name='语言')),
            ],
            options={
                'verbose_name': '落地页',
                'verbose_name_plural': '落地页',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DomainConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('block', models.BooleanField(default=True, verbose_name='开启/关闭')),
                ('cnzz', models.TextField(verbose_name='CNZZ统计代码')),
                ('facebook', models.TextField(verbose_name='Facebook')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='module_website.Domain', verbose_name='域名')),
                ('f_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_website.FloorPage', verbose_name='落地页')),
            ],
            options={
                'verbose_name': '域名配置',
                'verbose_name_plural': '域名配置',
                'ordering': ['-id'],
            },
        ),
    ]
