# Generated by Django 3.0.6 on 2020-05-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_website', '0003_domainconfig_is_save_service_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='域名'),
        ),
    ]
