# Generated by Django 3.0.6 on 2020-05-08 01:20

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('module_website', '0004_auto_20200507_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ip', models.GenericIPAddressField()),
                ('ssh_account', models.CharField(max_length=255, verbose_name='ssh账号')),
                ('ssh_password', models.CharField(max_length=255, verbose_name='ssh密码')),
                ('ssh_port', models.IntegerField(verbose_name='ssh端口')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
            },
        ),
    ]
