# Generated by Django 3.0.6 on 2020-05-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_website', '0005_websiteserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_website.WebsiteServer', verbose_name='主机'),
        ),
    ]
