# Generated by Django 3.0.6 on 2020-05-13 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_website', '0006_domain_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='域名所属'),
        ),
        migrations.AlterField(
            model_name='floorpage',
            name='link',
            field=models.CharField(help_text='落地页的域名,不要附带协议', max_length=255, verbose_name='落地页'),
        ),
    ]
