# Generated by Django 3.0.6 on 2020-05-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_website', '0008_auto_20200513_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteserver',
            name='local_host',
            field=models.CharField(max_length=255, null=True, verbose_name='内网IP'),
        ),
        migrations.AddField(
            model_name='websiteserver',
            name='server_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='服务器编号'),
        ),
    ]
