# Generated by Django 3.0.6 on 2020-05-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_website', '0009_auto_20200514_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteserver',
            name='www_root',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='网站根目录'),
        ),
    ]
