# Generated by Django 3.0.6 on 2020-05-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_website', '0010_websiteserver_www_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='dns',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DNS'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='expires_date',
            field=models.DateField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='register_author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='注册者'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='register_business',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='注册商'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='register_date',
            field=models.DateField(blank=True, null=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='register_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='注册网址'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='update_date',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
