# Generated by Django 3.0.6 on 2020-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_user', '0002_auto_20200506_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firegameuser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
